version: "3.8"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - 4200:4200
            - 49153:49153
        volumes:
            - type: bind
              source: ./client/src/app
              target: /usr/src/app
        depends_on:
          - back
    back:
        build:
            context: ./back
            dockerfile: Dockerfile
        ports:
            - 80:3000
        volumes:
            - type: bind
              source: ./back/index.js
              target: /express/index.js
            - type: bind
              source: ./client/dist
              target: /client/dist